name: Go Build and Release

#on:
#  push:
#    tags:
#      - 'v*'
on:
  push:
    branches: [ main ]


jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22' # Use the version of Go you need
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22'
      - name: Build binaries for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o pnc-tool-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o pnc-tool-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o pnc-tool-darwin-amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (Linux)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pnc-tool-linux-amd64
          asset_name: pnc-tool-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pnc-tool-windows-amd64.exe
          asset_name: pnc-tool-windows-amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload Release Asset (macOS)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pnc-tool-darwin-amd64
          asset_name: pnc-tool-darwin-amd64
          asset_content_type: application/octet-stream
